### ISSUE TITLE
dgCMatrix_colSums' not found error when using a binary matrix

### ISSUE THREAD

**Issue by rfarouni** [jlmelville/uwot#114] opened 2023-08-07 13:00 UTC
Hi,
On a binary matrix, the _umap_ function gives me this error

![Screenshot from 2023-08-07 14-58-07](https://github.com/jlmelville/uwot/assets/9895004/ed3fd329-aec6-41de-95f0-113930b17d00)

when I set _init="pca",_ I no longer get the error. I think the bug is in this line

https://github.com/jlmelville/uwot/blob/cef28ef5b2d080e9535fc2f0c724ea36538d698c/R/init.R#L94

Rick,

**Comment by jlmelville** [comment] 2023-08-07 15:05
Hi @rfarouni I am afraid I cannot reproduce this. It might help to paste the contents of `sessionInfo()` here and also to describe how you generated `binary_matrix`. For example, do you get the same problem if you run:

```R
set.seed(42)
sparse_matrix <- Matrix::rsparsematrix(nrow=20, ncol=20, density = 0.5)
sparse_matrix[sparse_matrix != 0] <- 1
 
umap(sparse_matrix, n_neighbors = 4, pca_center = FALSE)
```

The error message you are getting is not one I am familiar with, and suggests something pretty odd has happened with your system. If your packages are not all up to date, please try that.

**Comment by jlmelville** [comment] 2024-03-18 02:32
I am going to close this as not reproducible but please re-open if this is still a problem and there is more information

**Closed by jlmelville** 2024-03-18 02:32 UTC
